services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=http://localhost:5678/
     # adicionar api key aqui opcional
      # - ANTHROPIC_API_KEY=sk-ant-...
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      # Permite que o n8n (no Docker) aceda ao servidor MCP a correr no host (teu computador)
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
